from flask import Flask, render_template, request, jsonify
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.preprocessing import image as image_utils
import base64
from io import BytesIO
from PIL import Image
from keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.imagenet_utils import preprocess_input

app = Flask(__name__)

model = load_model('my_final_model4.hdf5')

class_names= ['Band_Aid','CD_player','Christmas_stocking','Crock_Pot','Dutch_oven','French_horn,_horn','French_loaf','Loafer','Windsor_tie','abacus','abaya',"academic_gown,_academic_robe,_judge's_robe",'accordion,_piano_accordion,_squeeze_box','acoustic_guitar','analog_clock','apron','ashcan,_trash_can,_garbage_can,_wastebin,_ash_bin,_ash-bin,_ashbin,_dustbin,_trash_barrel,_trash_bin','backpack,_back_pack,_knapsack,_packsack,_rucksack,_haversack','bagel,_beigel','balloon','ballpoint,_ballpoint_pen,_ballpen,_Biro','banjo','barbell','barometer','barrel,_cask','barrow,_garden_cart,_lawn_cart,_wheelbarrow','baseball','basketball','bassinet','bassoon','bath_towel','bathing_cap,_swimming_cap','beaker','bib','bicycle-built-for-two,_tandem_bicycle,_tandem','binder,_ring-binder','binoculars,_field_glasses,_opera_glasses','birdhouse','bonnet,_poke_bonnet','bookcase','bottlecap','bow','bow_tie,_bow-tie,_bowtie','brass,_memorial_tablet,_plaque','brassiere,_bra,_bandeau','broom','bucket,_pail','buckeye,_horse_chestnut,_conker','buckle','bulletproof_vest','caldron,_cauldron','can_opener,_tin_opener','candle,_taper,_wax_light','car_mirror','car_wheel','carbonara','cardigan','carton','cassette','cassette_player','cello,_violoncello','cellular_telephone,_cellular_phone,_cellphone,_cell,_mobile_phone','chain','chain_saw,_chainsaw','chainlink_fence','cheeseburger','chest','chiffonier,_commode','china_cabinet,_china_closet','chocolate_sauce,_chocolate_syrup','cleaver,_meat_cleaver,_chopper','cloak','clog,_geta,_patten,_sabot','cocktail_shaker','coffee_mug','coffeepot','combination_lock','comic_book','computer_keyboard,_keypad','corkscrew,_bottle_screw','cornet,_horn,_trumpet,_trump','cowboy_hat,_ten-gallon_hat','cradle','crash_helmet','crate','crib,_cot','croquet_ball','crossword_puzzle,_crossword','crutch','cup','daisy','desk','desktop_computer','dial_telephone,_dial_phone','digital_clock','digital_watch','dining_table,_board','dishrag,_dishcloth','dishwasher,_dish_washer,_dishwashing_machine','disk_brake,_disc_brake','doormat,_welcome_mat','dough','drum,_membranophone,_tympan','drumstick','dumbbell','eggnog','electric_fan,_blower','electric_guitar','entertainment_center','envelope','espresso_maker','face_powder','feather_boa,_boa','file,_file_cabinet,_filing_cabinet','fire_screen,_fireguard','flagpole,_flagstaff','flute,_transverse_flute','folding_chair','football_helmet','fountain_pen','four-poster','frying_pan,_frypan,_skillet','fur_coat','gasmask,_respirator,_gas_helmet','golf_ball','gown','grand_piano,_grand','guacamole','hair_slide','hair_spray','hammer','hamper','hand-held_computer,_hand-held_microcomputer','hand_blower,_blow_dryer,_blow_drier,_hair_dryer,_hair_drier','handkerchief,_hankie,_hanky,_hankey','hard_disc,_hard_disk,_fixed_disk','hatchet','honeycomb','hot_pot,_hotpot','hotdog,_hot_dog,_red_hot','hourglass','iPod','ice_lolly,_lolly,_lollipop,_popsicle','iron,_smoothing_iron','jean,_blue_jean,_denim','jersey,_T-shirt,_tee_shirt','jigsaw_puzzle','joystick','kimono','knee_pad','lab_coat,_laboratory_coat','ladle','lampshade,_lamp_shade','laptop,_laptop_computer','lawn_mower,_mower','lens_cap,_lens_cover','lighter,_light,_igniter,_ignitor','lipstick,_lip_rouge','lotion','loudspeaker,_speaker,_speaker_unit,_loudspeaker_system,_speaker_system','magnetic_compass','mailbag,_postbag','maillot','maillot,_tank_suit','maraca','marimba,_xylophone','mashed_potato','mask','matchstick','measuring_cup','meat_loaf,_meatloaf','medicine_chest,_medicine_cabinet','microphone,_mike','microwave,_microwave_oven','milk_can','miniskirt,_mini','mitten','mixing_bowl','modem','monitor','mortarboard','mosquito_net','mountain_bike,_all-terrain_bike,_off-roader','mountain_tent','mouse,_computer_mouse','mousetrap','mushroom','neck_brace','necklace','nipple','not_to_use','notebook,_notebook_computer','oil_filter','overskirt','oxygen_mask','padlock','paintbrush',"pajama,_pyjama,_pj's,_jammies",'panpipe,_pandean_pipe,_syrinx','paper_towel','pencil_box,_pencil_case','pencil_sharpener','perfume,_essence','piggy_bank,_penny_bank','pill_bottle','pillow','ping-pong_ball','pinwheel','pitcher,_ewer','plastic_bag','plate','plate_rack',"plunger,_plumber's_helper",'pole','pop_bottle,_soda_bottle','pot,_flowerpot',"potter's_wheel",'power_drill','prayer_rug,_prayer_mat','pretzel','printer','projector','puck,_hockey_puck','punching_bag,_punch_bag,_punching_ball,_punchball','purse','quill,_quill_pen','quilt,_comforter,_comfort,_puff','racket,_racquet','radio,_wireless','rain_barrel','reflex_camera','remote_control,_remote','rocking_chair,_rocker','rotisserie','rubber_eraser,_rubber,_pencil_eraser','rugby_ball','rule,_ruler','running_shoe','safety_pin','saltshaker,_salt_shaker','sandal','sarong','sax,_saxophone','scale,_weighing_machine','screen,_CRT_screen','screw','screwdriver','sewing_machine','shopping_basket','shopping_cart','shovel','shower_cap','shower_curtain','ski_mask','sleeping_bag','slide_rule,_slipstick','sliding_door','snorkel','soap_dispenser','soccer_ball','sock','sombrero','soup_bowl','space_bar','space_heater','spatula','spotlight,_spot','steel_drum','stethoscope','stopwatch,_stop_watch','stove','strainer','studio_couch,_day_bed','suit,_suit_of_clothes','sunglass','sunglasses,_dark_glasses,_shades','sunscreen,_sunblock,_sun_blocker','swab,_swob,_mop','sweatshirt','swimming_trunks,_bathing_trunks','swing','switch,_electric_switch,_electrical_switch','table_lamp','tape_player','teapot','teddy,_teddy_bear','television,_television_system','tennis_ball','thimble','toaster','toilet_tissue,_toilet_paper,_bathroom_tissue','torch','tray','trench_coat','trifle','tripod','trombone','typewriter_keyboard','umbrella','upright,_upright_piano','vacuum,_vacuum_cleaner','vase','violin,_fiddle','volleyball','waffle_iron','wall_clock','wallet,_billfold,_notecase,_pocketbook','wardrobe,_closet,_press','washbasin,_handbasin,_washbowl,_lavabo,_wash-hand_basin','washer,_automatic_washer,_washing_machine','water_bottle','water_jug','whistle','wig','window_screen','window_shade','wok','wooden_spoon','wool,_woolen,_woollen']

newItems = ["abacus -- Eğitim -- Kırtasiye", "abaya -- Giyim ve Aksesuar -- Yazlık", "academic gown, academic robe, judge's robe -- Giyim ve Aksesuar -- Resmi", "accordion, piano accordion, squeeze box -- Hobi ve Eğlence -- Müzik", "acoustic guitar -- Hobi ve Eğlence -- Müzik", "analog clock -- Ev Eşyaları -- Mobilya", "apron -- Bebek ve Çocuk -- Giyim", "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin -- Ev Eşyaları -- Mobilya", "backpack, back pack, knapsack, packsack, rucksack, haversack -- Eğitim -- Kırtasiye", "balloon -- Hobi ve Eğlence -- Oyun", "ballpoint, ballpoint pen, ballpen, Biro -- Eğitim -- Kırtasiye", "Band Aid -- Diğer -- Diğer", "banjo -- Hobi ve Eğlence -- Müzik", "barbell -- Spor ve Outdoor -- Gym", "barometer -- Diğer -- Diğer", "barrel, cask -- Ev Eşyaları -- Bahçe", "barrow, garden cart, lawn cart, wheelbarrow -- Ev Eşyaları -- Bahçe", "baseball -- Spor ve Outdoor -- Top", "basketball -- Spor ve Outdoor -- Top", "bassinet -- Bebek ve Çocuk -- Giyim", "bassoon -- Hobi ve Eğlence -- Müzik", "bathing cap, swimming cap -- Spor ve Outdoor -- Koruma", "bath towel -- Ev Eşyaları -- Mobilya", "beaker -- Eğitim -- Kırtasiye", "bib -- Bebek ve Çocuk -- Giyim", "bicycle-built-for-two, tandem bicycle, tandem -- Spor ve Outdoor -- Gym", "binder, ring-binder -- Eğitim -- Kırtasiye", "binoculars, field glasses, opera glasses -- Hobi ve Eğlence -- Oyun", "birdhouse -- Diğer -- Diğer", "bonnet, poke bonnet -- Bebek ve Çocuk -- Giyim", "bookcase -- Ev Eşyaları -- Mobilya", "bottlecap -- Diğer -- Diğer", "bow -- Spor ve Outdoor -- Gym", "bow tie, bow-tie, bowtie -- Giyim ve Aksesuar -- Resmi", "brass, memorial tablet, plaque -- Diğer -- Diğer", "brassiere, bra, bandeau -- Giyim ve Aksesuar -- Yazlık", "broom -- Ev Eşyaları -- Bahçe", "bucket, pail -- Ev Eşyaları -- Mutfak", "buckle -- Giyim ve Aksesuar -- Aksesuar", "bulletproof vest -- Spor ve Outdoor -- Koruma", "caldron, cauldron -- Ev Eşyaları -- Mutfak", "candle, taper, wax light -- Diğer -- Diğer", "can opener, tin opener -- Ev Eşyaları -- Mutfak", "cardigan -- Giyim ve Aksesuar -- Kışlık", "car mirror -- Diğer -- Diğer", "carton -- Diğer -- Diğer", "car wheel -- Diğer -- Diğer", "cassette -- Hobi ve Eğlence -- Müzik", "cassette player -- Hobi ve Eğlence -- Müzik", "CD player -- Hobi ve Eğlence -- Müzik", "cello, violoncello -- Hobi ve Eğlence -- Müzik", "cellular telephone, cellular phone, cellphone, cell, mobile phone -- Elektronik -- Bilgisayar & Telefon", "chain -- Giyim ve Aksesuar -- Aksesuar", "chainlink fence -- Ev Eşyaları -- Bahçe", "chain saw, chainsaw -- Ev Eşyaları -- Bahçe", "chest -- Ev Eşyaları -- Mobilya", "chiffonier, commode -- Ev Eşyaları -- Mobilya", "china cabinet, china closet -- Ev Eşyaları -- Mobilya", "Christmas stocking -- Giyim ve Aksesuar -- Kışlık", "cleaver, meat cleaver, chopper -- Ev Eşyaları -- Mutfak", "cloak -- Giyim ve Aksesuar -- Kışlık", "clog, geta, patten, sabot -- Giyim ve Aksesuar -- Yazlık", "cocktail shaker -- Elektronik -- Pişirme", "coffee mug -- Ev Eşyaları -- Mutfak", "coffeepot -- Ev Eşyaları -- Mutfak", "combination lock -- Diğer -- Diğer", "computer keyboard, keypad -- Elektronik -- Bilgisayar & Telefon", "corkscrew, bottle screw -- Ev Eşyaları -- Mutfak", "cornet, horn, trumpet, trump -- Hobi ve Eğlence -- Müzik", "cowboy hat, ten-gallon hat -- Giyim ve Aksesuar -- Yazlık", "cradle -- Bebek ve Çocuk -- Giyim", "crash helmet -- Spor ve Outdoor -- Koruma", "crate -- Ev Eşyaları -- Bahçe", "crib, cot -- Bebek ve Çocuk -- Giyim", "Crock Pot -- Ev Eşyaları -- Mutfak", "croquet ball -- Spor ve Outdoor -- Top", "crutch -- Diğer -- Diğer", "desk -- Ev Eşyaları -- Mobilya", "desktop computer -- Elektronik -- Bilgisayar & Telefon", "dial telephone, dial phone -- Elektronik -- Bilgisayar & Telefon", "digital clock -- Elektronik -- Bilgisayar & Telefon", "digital watch -- Elektronik -- Bilgisayar & Telefon", "dining table, board -- Ev Eşyaları -- Mutfak", "dishrag, dishcloth -- Diğer -- Diğer", "dishwasher, dish washer, dishwashing machine -- Elektronik -- Temizlik", "disk brake, disc brake -- Spor ve Outdoor -- Koruma", "doormat, welcome mat -- Ev Eşyaları -- Bahçe", "drum, membranophone, tympan -- Hobi ve Eğlence -- Müzik", "drumstick -- Hobi ve Eğlence -- Müzik", "dumbbell -- Spor ve Outdoor -- Gym", "Dutch oven -- Ev Eşyaları -- Mutfak", "electric fan, blower -- Elektronik -- Temizlik", "electric guitar -- Hobi ve Eğlence -- Müzik", "entertainment center -- Elektronik -- Oyun", "envelope -- Eğitim -- Kırtasiye", "espresso maker -- Elektronik -- Pişirme", "face powder -- Giyim ve Aksesuar -- Aksesuar", "feather boa, boa -- Giyim ve Aksesuar -- Kışlık", "file, file cabinet, filing cabinet -- Ev Eşyaları -- Mobilya", "fire screen, fireguard -- Elektronik -- Fotoğraf & Kamera", "flagpole, flagstaff -- Diğer -- Diğer", "flute, transverse flute -- Hobi ve Eğlence -- Müzik", "folding chair -- Ev Eşyaları -- Mobilya", "football helmet -- Spor ve Outdoor -- Koruma", "fountain pen -- Eğitim -- Kırtasiye", "four-poster -- Ev Eşyaları -- Mobilya", "French horn, horn -- Hobi ve Eğlence -- Müzik", "frying pan, frypan, skillet -- Ev Eşyaları -- Mutfak", "fur coat -- Giyim ve Aksesuar -- Kışlık", "gasmask, respirator, gas helmet -- Diğer -- Diğer", "golf ball -- Spor ve Outdoor -- Top", "gown -- Giyim ve Aksesuar -- Resmi", "grand piano, grand -- Hobi ve Eğlence -- Müzik", "hair slide -- Giyim ve Aksesuar -- Aksesuar", "hair spray -- Giyim ve Aksesuar -- Aksesuar", "hammer -- Diğer -- Diğer", "hamper -- Diğer -- Diğer", "hand blower, blow dryer, blow drier, hair dryer, hair drier -- Elektronik -- Temizlik", "hand-held computer, hand-held microcomputer -- Elektronik -- Bilgisayar & Telefon", "handkerchief, hankie, hanky, hankey -- Giyim ve Aksesuar -- Aksesuar", "hard disc, hard disk, fixed disk -- Elektronik -- Bilgisayar & Telefon", "hatchet -- Diğer -- Diğer", "honeycomb -- Diğer -- Diğer", "hourglass -- Ev Eşyaları -- Mobilya", "iPod -- Elektronik -- Bilgisayar & Telefon", "iron, smoothing iron -- Elektronik -- Temizlik", "jean, blue jean, denim -- Giyim ve Aksesuar -- Yazlık", "jersey, T-shirt, tee shirt -- Giyim ve Aksesuar -- Yazlık", "jigsaw puzzle -- Hobi ve Eğlence -- Oyun", "joystick -- Hobi ve Eğlence -- Oyun", "kimono -- Giyim ve Aksesuar -- Resmi", "knee pad -- Spor ve Outdoor -- Koruma", "lab coat, laboratory coat -- Giyim ve Aksesuar -- Resmi", "ladle -- Ev Eşyaları -- Mutfak", "lampshade, lamp shade -- Ev Eşyaları -- Mobilya", "laptop, laptop computer -- Elektronik -- Bilgisayar & Telefon", "lawn mower, mower -- Elektronik -- Temizlik", "lens cap, lens cover -- Diğer -- Diğer", "lighter, light, igniter, ignitor -- Diğer -- Diğer", "lipstick, lip rouge -- Giyim ve Aksesuar -- Aksesuar", "Loafer -- Giyim ve Aksesuar -- Kışlık", "lotion -- Giyim ve Aksesuar -- Aksesuar", "loudspeaker, speaker, speaker unit, loudspeaker system, speaker system -- Elektronik -- Bilgisayar & Telefon", "magnetic compass -- Diğer -- Diğer", "mailbag, postbag -- Eğitim -- Kırtasiye", "maillot -- Giyim ve Aksesuar -- Yazlık", "maillot, tank suit -- Giyim ve Aksesuar -- Yazlık", "maraca -- Bebek ve Çocuk -- Oyuncak", "marimba, xylophone -- Hobi ve Eğlence -- Müzik", "mask -- Giyim ve Aksesuar -- Aksesuar", "matchstick -- Diğer -- Diğer", "measuring cup -- Ev Eşyaları -- Mutfak", "medicine chest, medicine cabinet -- Ev Eşyaları -- Mobilya", "microphone, mike -- Elektronik -- Bilgisayar & Telefon", "microwave, microwave oven -- Elektronik -- Pişirme", "milk can -- Ev Eşyaları -- Mutfak", "miniskirt, mini -- Giyim ve Aksesuar -- Yazlık", "mitten -- Giyim ve Aksesuar -- Kışlık", "mixing bowl -- Ev Eşyaları -- Mutfak", "modem -- Elektronik -- Bilgisayar & Telefon", "monitor -- Elektronik -- Fotoğraf & Kamera", "mortarboard -- Eğitim -- Kırtasiye", "mosquito net -- Ev Eşyaları -- Mobilya", "mountain bike, all-terrain bike, off-roader -- Spor ve Outdoor -- Gym", "mountain tent -- Hobi ve Eğlence -- Oyun", "mouse, computer mouse -- Elektronik -- Bilgisayar & Telefon", "mousetrap -- Diğer -- Diğer", "neck brace -- Diğer -- Diğer", "necklace -- Giyim ve Aksesuar -- Aksesuar", "notebook, notebook computer -- Elektronik -- Bilgisayar & Telefon", "nipple -- Bebek ve Çocuk -- Oyuncak", "oil filter -- Diğer -- Diğer", "overskirt -- Giyim ve Aksesuar -- Kışlık", "oxygen mask -- Diğer -- Diğer", "padlock -- Diğer -- Diğer", "paintbrush -- Hobi ve Eğlence -- Oyun", "pajama, pyjama, pj's, jammies -- Giyim ve Aksesuar -- Yazlık", "panpipe, pandean pipe, syrinx -- Hobi ve Eğlence -- Müzik", "paper towel -- Ev Eşyaları -- Mobilya", "pencil box, pencil case -- Eğitim -- Kırtasiye", "pencil sharpener -- Eğitim -- Kırtasiye", "perfume, essence -- Giyim ve Aksesuar -- Aksesuar", "piggy bank, penny bank -- Diğer -- Diğer", "pill bottle -- Diğer -- Diğer", "pillow -- Ev Eşyaları -- Mobilya", "ping-pong ball -- Spor ve Outdoor -- Top", "pinwheel -- Hobi ve Eğlence -- Oyun", "pitcher, ewer -- Ev Eşyaları -- Mutfak", "plastic bag -- Diğer -- Diğer", "plate rack -- Ev Eşyaları -- Mutfak", "plunger, plumber's helper -- Ev Eşyaları -- Mobilya", "pole -- Spor ve Outdoor -- Gym", "pop bottle, soda bottle -- Diğer -- Diğer", "pot, flowerpot -- Diğer -- Diğer", "potter's wheel -- Diğer -- Diğer", "power drill -- Elektronik -- Diğer", "prayer rug, prayer mat -- Diğer -- Diğer", "printer -- Elektronik -- Fotoğraf & Kamera", "projector -- Elektronik -- Fotoğraf & Kamera", "puck, hockey puck -- Spor ve Outdoor -- Top", "punching bag, punch bag, punching ball, punchball -- Spor ve Outdoor -- Gym", "purse -- Giyim ve Aksesuar -- Resmi", "quill, quill pen -- Eğitim -- Kırtasiye", "quilt, comforter, comfort, puff -- Ev Eşyaları -- Mobilya", "racket, racquet -- Spor ve Outdoor -- Top", "radio, wireless -- Elektronik -- Bilgisayar & Telefon", "rain barrel -- Ev Eşyaları -- Bahçe", "reflex camera -- Elektronik -- Fotoğraf & Kamera", "remote control, remote -- Elektronik -- Oyun", "rocking chair, rocker -- Ev Eşyaları -- Bahçe", "rotisserie -- Ev Eşyaları -- Mutfak", "rubber eraser, rubber, pencil eraser -- Eğitim -- Kırtasiye", "rugby ball -- Spor ve Outdoor -- Top", "rule, ruler -- Eğitim -- Kırtasiye", "running shoe -- Giyim ve Aksesuar -- Yazlık", "safety pin -- Diğer -- Diğer", "saltshaker, salt shaker -- Ev Eşyaları -- Mutfak", "sandal -- Giyim ve Aksesuar -- Yazlık", "sarong -- Giyim ve Aksesuar -- Yazlık", "sax, saxophone -- Hobi ve Eğlence -- Müzik", "scale, weighing machine -- Elektronik -- Diğer", "screen, CRT screen -- Elektronik -- Fotoğraf & Kamera", "screw -- Diğer -- Diğer", "screwdriver -- Diğer -- Diğer", "sewing machine -- Elektronik -- Diğer", "shopping basket -- Diğer -- Diğer", "shopping cart -- Diğer -- Diğer", "shovel -- Ev Eşyaları -- Bahçe", "shower cap -- Giyim ve Aksesuar -- Yazlık", "shower curtain -- Ev Eşyaları -- Mobilya", "ski mask -- Diğer -- Diğer", "sleeping bag -- Hobi ve Eğlence -- Oyun", "slide rule, slipstick -- Eğitim -- Kırtasiye", "sliding door -- Ev Eşyaları -- Mobilya", "snorkel -- Spor ve Outdoor -- Koruma", "soap dispenser -- Ev Eşyaları -- Mobilya", "soccer ball -- Spor ve Outdoor -- Top", "sock -- Giyim ve Aksesuar -- Kışlık", "sombrero -- Giyim ve Aksesuar -- Aksesuar", "soup bowl -- Ev Eşyaları -- Mutfak", "space bar -- Diğer -- Diğer", "space heater -- Elektronik -- Diğer", "spatula -- Ev Eşyaları -- Mutfak", "spotlight, spot -- Elektronik -- Diğer", "steel drum -- Hobi ve Eğlence -- Müzik", "stethoscope -- Eğitim -- Kırtasiye", "stopwatch, stop watch -- Elektronik -- Diğer", "stove -- Ev Eşyaları -- Mutfak", "strainer -- Ev Eşyaları -- Mutfak", "studio couch, day bed -- Ev Eşyaları -- Mobilya", "suit, suit of clothes -- Giyim ve Aksesuar -- Resmi", "sunglass -- Giyim ve Aksesuar -- Yazlık", "sunglasses, dark glasses, shades -- Giyim ve Aksesuar -- Yazlık", "sunscreen, sunblock, sun blocker -- Giyim ve Aksesuar -- Aksesuar", "swab, swob, mop -- Ev Eşyaları -- Mobilya", "sweatshirt -- Giyim ve Aksesuar -- Kışlık", "swimming trunks, bathing trunks -- Giyim ve Aksesuar -- Yazlık", "swing -- Diğer -- Diğer", "switch, electric switch, electrical switch -- Elektronik -- Diğer", "table lamp -- Elektronik -- Diğer", "tape player -- Elektronik -- Diğer", "teapot -- Ev Eşyaları -- Mutfak", "teddy, teddy bear -- Hobi ve Eğlence -- Oyun", "television, television system -- Elektronik -- Fotoğraf & Kamera", "tennis ball -- Spor ve Outdoor -- Top", "thimble -- Diğer -- Diğer", "toaster -- Elektronik -- Pişirme", "torch -- Elektronik -- Pişirme", "tray -- Ev Eşyaları -- Mutfak", "trench coat -- Giyim ve Aksesuar -- Kışlık", "tripod -- Diğer -- Diğer", "trombone -- Hobi ve Eğlence -- Müzik", "typewriter keyboard -- Hobi ve Eğlence -- Oyun", "umbrella -- Diğer -- Diğer", "upright, upright piano -- Hobi ve Eğlence -- Müzik", "vacuum, vacuum cleaner -- Elektronik -- Temizlik", "vase -- Ev Eşyaları -- Mobilya", "violin, fiddle -- Hobi ve Eğlence -- Müzik", "volleyball -- Spor ve Outdoor -- Top", "waffle iron -- Elektronik -- Pişirme", "wall clock -- Ev Eşyaları -- Mobilya", "wallet, billfold, notecase, pocketbook -- Diğer -- Diğer", "wardrobe, closet, press -- Ev Eşyaları -- Mobilya", "washbasin, handbasin, washbowl, lavabo, wash-hand basin -- Ev Eşyaları -- Mobilya", "washer, automatic washer, washing machine -- Elektronik -- Temizlik", "water bottle -- Diğer -- Diğer", "water jug -- Diğer -- Diğer", "whistle -- Spor ve Outdoor -- Top", "wig -- Giyim ve Aksesuar -- Aksesuar", "window screen -- Ev Eşyaları -- Bahçe", "window shade -- Ev Eşyaları -- Mobilya", "Windsor tie -- Giyim ve Aksesuar -- Resmi", "wok -- Ev Eşyaları -- Mutfak", "wooden spoon -- Ev Eşyaları -- Mutfak", "wool, woolen, woollen -- Ev Eşyaları -- Mobilya", "comic book -- Hobi ve Eğlence -- Oyun", "crossword puzzle, crossword -- Hobi ve Eğlence -- Oyun", "plate -- Ev Eşyaları -- Mutfak", "guacamole -- Diğer -- Diğer", "hot pot, hotpot -- Ev Eşyaları -- Mutfak", "trifle -- Diğer -- Diğer", "ice lolly, lolly, lollipop, popsicle -- Bebek ve Çocuk -- Oyuncak", "French loaf -- Diğer -- Diğer", "bagel, beigel -- Diğer -- Diğer", "pretzel -- Diğer -- Diğer", "cheeseburger -- Diğer -- Diğer", "hotdog, hot dog, red hot -- Diğer -- Diğer", "mashed potato -- Diğer -- Diğer", "mushroom -- Diğer -- Diğer", "carbonara -- Diğer -- Diğer", "chocolate sauce, chocolate syrup -- Diğer -- Diğer", "dough -- Diğer -- Diğer", "meat loaf, meatloaf -- Diğer -- Diğer", "cup -- Ev Eşyaları -- Mutfak", "eggnog -- Diğer -- Diğer", "daisy -- Diğer -- Diğer", "buckeye, horse chestnut, conker -- Diğer -- Diğer", "toilet tissue, toilet paper, bathroom tissue -- Ev Eşyaları -- Mobilya"]

subsubEng = {'Bebek ve Çocuk': {'Giyim': ['apron',
                              'bassinet',
                              'bib',
                              'bonnet, poke bonnet',
                              'cradle',
                              'crib, cot'],
                    'Oyuncak': ['maraca',
                                'nipple',
                                'ice lolly, lolly, lollipop, popsicle']},
 'Diğer': {'Diğer': ['Band Aid',
                     'barometer',
                     'birdhouse',
                     'bottlecap',
                     'brass, memorial tablet, plaque',
                     'candle, taper, wax light',
                     'car mirror',
                     'carton',
                     'car wheel',
                     'combination lock',
                     'crutch',
                     'dishrag, dishcloth',
                     'flagpole, flagstaff',
                     'gasmask, respirator, gas helmet',
                     'hammer',
                     'hamper',
                     'hatchet',
                     'honeycomb',
                     'lens cap, lens cover',
                     'lighter, light, igniter, ignitor',
                     'magnetic compass',
                     'matchstick',
                     'mousetrap',
                     'neck brace',
                     'oil filter',
                     'oxygen mask',
                     'padlock',
                     'piggy bank, penny bank',
                     'pill bottle',
                     'plastic bag',
                     'pop bottle, soda bottle',
                     'pot, flowerpot',
                     "potter's wheel",
                     'prayer rug, prayer mat',
                     'safety pin',
                     'screw',
                     'screwdriver',
                     'shopping basket',
                     'shopping cart',
                     'ski mask',
                     'space bar',
                     'swing',
                     'thimble',
                     'tripod',
                     'umbrella',
                     'wallet, billfold, notecase, pocketbook',
                     'water bottle',
                     'water jug',
                     'guacamole',
                     'trifle',
                     'French loaf',
                     'bagel, beigel',
                     'pretzel',
                     'cheeseburger',
                     'hotdog, hot dog, red hot',
                     'mashed potato',
                     'mushroom',
                     'carbonara',
                     'chocolate sauce, chocolate syrup',
                     'dough',
                     'meat loaf, meatloaf',
                     'eggnog',
                     'daisy',
                     'buckeye, horse chestnut, conker']},
 'Elektronik': {'Bilgisayar & Telefon': ['cellular telephone, cellular phone, '
                                         'cellphone, cell, mobile phone',
                                         'computer keyboard, keypad',
                                         'desktop computer',
                                         'dial telephone, dial phone',
                                         'digital clock',
                                         'digital watch',
                                         'hand-held computer, hand-held '
                                         'microcomputer',
                                         'hard disc, hard disk, fixed disk',
                                         'iPod',
                                         'laptop, laptop computer',
                                         'loudspeaker, speaker, speaker unit, '
                                         'loudspeaker system, speaker system',
                                         'microphone, mike',
                                         'modem',
                                         'mouse, computer mouse',
                                         'notebook, notebook computer',
                                         'radio, wireless'],
                'Diğer': ['power drill',
                          'scale, weighing machine',
                          'sewing machine',
                          'space heater',
                          'spotlight, spot',
                          'stopwatch, stop watch',
                          'switch, electric switch, electrical switch',
                          'table lamp',
                          'tape player'],
                'Fotoğraf & Kamera': ['fire screen, fireguard',
                                      'monitor',
                                      'printer',
                                      'projector',
                                      'reflex camera',
                                      'screen, CRT screen',
                                      'television, television system'],
                'Oyun': ['entertainment center', 'remote control, remote'],
                'Pişirme': ['cocktail shaker',
                            'espresso maker',
                            'microwave, microwave oven',
                            'toaster',
                            'torch',
                            'waffle iron'],
                'Temizlik': ['dishwasher, dish washer, dishwashing machine',
                             'electric fan, blower',
                             'hand blower, blow dryer, blow drier, hair dryer, '
                             'hair drier',
                             'iron, smoothing iron',
                             'lawn mower, mower',
                             'vacuum, vacuum cleaner',
                             'washer, automatic washer, washing machine']},
 'Ev Eşyaları': {'Bahçe': ['barrel, cask',
                           'barrow, garden cart, lawn cart, wheelbarrow',
                           'broom',
                           'chainlink fence',
                           'chain saw, chainsaw',
                           'crate',
                           'doormat, welcome mat',
                           'rain barrel',
                           'rocking chair, rocker',
                           'shovel',
                           'window screen'],
                 'Mobilya': ['analog clock',
                             'ashcan, trash can, garbage can, wastebin, ash '
                             'bin, ash-bin, ashbin, dustbin, trash barrel, '
                             'trash bin',
                             'bath towel',
                             'bookcase',
                             'chest',
                             'chiffonier, commode',
                             'china cabinet, china closet',
                             'desk',
                             'file, file cabinet, filing cabinet',
                             'folding chair',
                             'four-poster',
                             'hourglass',
                             'lampshade, lamp shade',
                             'medicine chest, medicine cabinet',
                             'mosquito net',
                             'paper towel',
                             'pillow',
                             "plunger, plumber's helper",
                             'quilt, comforter, comfort, puff',
                             'shower curtain',
                             'sliding door',
                             'soap dispenser',
                             'studio couch, day bed',
                             'swab, swob, mop',
                             'vase',
                             'wall clock',
                             'wardrobe, closet, press',
                             'washbasin, handbasin, washbowl, lavabo, '
                             'wash-hand basin',
                             'window shade',
                             'wool, woolen, woollen',
                             'toilet tissue, toilet paper, bathroom tissue'],
                 'Mutfak': ['bucket, pail',
                            'caldron, cauldron',
                            'can opener, tin opener',
                            'cleaver, meat cleaver, chopper',
                            'coffee mug',
                            'coffeepot',
                            'corkscrew, bottle screw',
                            'Crock Pot',
                            'dining table, board',
                            'Dutch oven',
                            'frying pan, frypan, skillet',
                            'ladle',
                            'measuring cup',
                            'milk can',
                            'mixing bowl',
                            'pitcher, ewer',
                            'plate rack',
                            'rotisserie',
                            'saltshaker, salt shaker',
                            'soup bowl',
                            'spatula',
                            'stove',
                            'strainer',
                            'teapot',
                            'tray',
                            'wok',
                            'wooden spoon',
                            'plate',
                            'hot pot, hotpot',
                            'cup']},
 'Eğitim': {'Kırtasiye': ['abacus',
                          'backpack, back pack, knapsack, packsack, rucksack, '
                          'haversack',
                          'ballpoint, ballpoint pen, ballpen, Biro',
                          'beaker',
                          'binder, ring-binder',
                          'envelope',
                          'fountain pen',
                          'mailbag, postbag',
                          'mortarboard',
                          'pencil box, pencil case',
                          'pencil sharpener',
                          'quill, quill pen',
                          'rubber eraser, rubber, pencil eraser',
                          'rule, ruler',
                          'slide rule, slipstick',
                          'stethoscope']},
 'Giyim ve Aksesuar': {'Aksesuar': ['buckle',
                                    'chain',
                                    'face powder',
                                    'hair slide',
                                    'hair spray',
                                    'handkerchief, hankie, hanky, hankey',
                                    'lipstick, lip rouge',
                                    'lotion',
                                    'mask',
                                    'necklace',
                                    'perfume, essence',
                                    'sombrero',
                                    'sunscreen, sunblock, sun blocker',
                                    'wig'],
                       'Kışlık': ['cardigan',
                                  'Christmas stocking',
                                  'cloak',
                                  'feather boa, boa',
                                  'fur coat',
                                  'Loafer',
                                  'mitten',
                                  'overskirt',
                                  'sock',
                                  'sweatshirt',
                                  'trench coat'],
                       'Resmi': ["academic gown, academic robe, judge's robe",
                                 'bow tie, bow-tie, bowtie',
                                 'gown',
                                 'kimono',
                                 'lab coat, laboratory coat',
                                 'purse',
                                 'suit, suit of clothes',
                                 'Windsor tie'],
                       'Yazlık': ['abaya',
                                  'brassiere, bra, bandeau',
                                  'clog, geta, patten, sabot',
                                  'cowboy hat, ten-gallon hat',
                                  'jean, blue jean, denim',
                                  'jersey, T-shirt, tee shirt',
                                  'maillot',
                                  'maillot, tank suit',
                                  'miniskirt, mini',
                                  "pajama, pyjama, pj's, jammies",
                                  'running shoe',
                                  'sandal',
                                  'sarong',
                                  'shower cap',
                                  'sunglass',
                                  'sunglasses, dark glasses, shades',
                                  'swimming trunks, bathing trunks']},
 'Hobi ve Eğlence': {'Müzik': ['accordion, piano accordion, squeeze box',
                               'acoustic guitar',
                               'banjo',
                               'bassoon',
                               'cassette',
                               'cassette player',
                               'CD player',
                               'cello, violoncello',
                               'cornet, horn, trumpet, trump',
                               'drum, membranophone, tympan',
                               'drumstick',
                               'electric guitar',
                               'flute, transverse flute',
                               'French horn, horn',
                               'grand piano, grand',
                               'marimba, xylophone',
                               'panpipe, pandean pipe, syrinx',
                               'sax, saxophone',
                               'steel drum',
                               'trombone',
                               'upright, upright piano',
                               'violin, fiddle'],
                     'Oyun': ['balloon',
                              'binoculars, field glasses, opera glasses',
                              'jigsaw puzzle',
                              'joystick',
                              'mountain tent',
                              'paintbrush',
                              'pinwheel',
                              'sleeping bag',
                              'teddy, teddy bear',
                              'typewriter keyboard',
                              'comic book',
                              'crossword puzzle, crossword']},
 'Spor ve Outdoor': {'Gym': ['barbell',
                             'bicycle-built-for-two, tandem bicycle, tandem',
                             'bow',
                             'dumbbell',
                             'mountain bike, all-terrain bike, off-roader',
                             'pole',
                             'punching bag, punch bag, punching ball, '
                             'punchball'],
                     'Koruma': ['bathing cap, swimming cap',
                                'bulletproof vest',
                                'crash helmet',
                                'disk brake, disc brake',
                                'football helmet',
                                'knee pad',
                                'snorkel'],
                     'Top': ['baseball',
                             'basketball',
                             'croquet ball',
                             'golf ball',
                             'ping-pong ball',
                             'puck, hockey puck',
                             'racket, racquet',
                             'rugby ball',
                             'soccer ball',
                             'tennis ball',
                             'volleyball',
                             'whistle']}}

subsubTur = data = {'Bebek ve Çocuk': {'Giyim': ['apron',
                              'beşik',
                              'Bebek Önlüğü',
                              'bonet',
                              'kızak',
                              'karyola'],
                    'Oyuncak': ['marakas',
                                'emzik',
                                'dondurma']},
 'Diğer': {'Diğer': ['Yara Bandı',
                     'barometre',
                     'kuş yuvası',
                     'şişe kapağı',
                     'plaket',
                     'mum',
                     'araba aynası',
                     'karton',
                     'araba tekerleği',
                     'kombinasyon kilidi',
                     'koltuk değneği',
                     'bulaşık bezi',
                     'bayrak direği',
                     'gaz maskesi',
                     'çekiç',
                     'sepet',
                     'balta',
                     'petek',
                     'lens kapağı',
                     'çakmak',
                     'manyetik pusula',
                     'kibrit çöpü',
                     'fare kapanı',
                     'boyunluk',
                     'yağ filtresi',
                     'oksijen maskesi',
                     'asma kilit',
                     'kumbarası',
                     'hap şişesi',
                     'plastik torba',
                     'gazoz şişesi',
                     'saksı',
                     'çömlekçi çarkı',
                     'namazlık',
                     'çengelli iğne',
                     'vida',
                     'tornavida',
                     'alışveriş sepeti',
                     'alışveriş arabası',
                     'kayak maskesi',
                     'boşluk tuşu',
                     'salıncak',
                     'yüksük',
                     'tripod',
                     'şemsiye',
                     'cüzdan',
                     'su şişesi',
                     'su sürahisi',
                     'guacamole',
                     'trifle',
                     'Fransız ekmeği',
                     'simit',
                     'pretzel',
                     'cheeseburger',
                     'sosisli sandviç',
                     'püre',
                     'mantar',
                     'carbonara',
                     'çikolata sosu',
                     'hamur',
                     'rulo köfte',
                     'yumurta likörü',
                     'papatya',
                     'kestane']},
'Elektronik': {'Bilgisayar & Telefon': ['cep telefonu',
                                         'bilgisayar klavyesi',
                                         'masaüstü bilgisayar',
                                         'çevirmeli telefon',
                                         'dijital saat',
                                         'dijital kol saati',
                                         'el bilgisayarı',
                                         'sabit disk',
                                         'iPod',
                                         'dizüstü bilgisayar',
                                         'hoparlör',
                                         'mikrofon',
                                         'modem',
                                         'bilgisayar faresi',
                                         'notebook',
                                         'radyo'],
                'Diğer': ['matkap',
                          'terazi',
                          'dikiş makinesi',
                          'ısıtıcı',
                          'spot ışığı',
                          'kronometre',
                          'elektrik anahtarı',
                          'masa lambası',
                          'teyp çalar'],
                'Fotoğraf & Kamera': ['ateş ekranı',
                                      'monitör',
                                      'yazıcı',
                                      'projeksiyon cihazı',
                                      'refleks kamera',
                                      'ekran',
                                      'televizyon'],
                'Oyun': ['eğlence merkezi', 'uzaktan kumanda'],
                'Pişirme': ['kokteyl çalkalayıcı',
                            'espresso makinesi',
                            'mikrodalga fırın',
                            'ekmek kızartma makinesi',
                            'el feneri',
                            'waffle makinesi'],
                'Temizlik': ['bulaşık makinesi',
                             'elektrikli fan',
                             'saç kurutma makinesi',
                             'ütü',
                             'çim biçme makinesi',
                             'elektrik süpürgesi',
                             'çamaşır makinesi']},
'Ev Eşyaları': {'Bahçe': ['varil',
                           'el arabası',
                           'süpürge',
                           'çit',
                           'zincirli testere',
                           'sandık',
                           'paspas',
                           'yağmur varili',
                           'sallanan sandalye',
                           'kürek',
                           'pencere teli'],
                 'Mobilya': ['analog saat',
                             'çöp kutusu',
                             'banyo havlusu',
                             'kitaplık',
                             'sandık',
                             'komodin',
                             'vitrin',
                             'çalışma masası',
                             'dosya dolabı',
                             'katlanır sandalye',
                             'dört direkli yatak',
                             'kum saati',
                             'lamba şapkası',
                             'ilaç dolabı',
                             'sinek teli',
                             'kağıt havlu',
                             'yastık',
                             'tuvalet pompası',
                             'yorgan',
                             'duş perdesi',
                             'sürgülü kapı',
                             'sabunluk',
                             'çekyat',
                             'paspas',
                             'vazo',
                             'duvar saati',
                             'gardırop',
                             'lavabo',
                             'stor perde',
                             'yün',
                             'tuvalet kağıdı'],
                 'Mutfak': ['kova',
                            'kazan',
                            'konserve açacağı',
                            'satır',
                            'kahve kupası',
                            'kahve cezvesi',
                            'tirbuşon',
                            'yavaş pişirici',
                            'yemek masası',
                            'döküm tencere',
                            'kızartma tavası',
                            'kepçe',
                            'ölçü kabı',
                            'süt tenekesi',
                            'karıştırma kabı',
                            'sürahi',
                            'tabak rafı',
                            'çevirme makinesi',
                            'tuzluk',
                            'çorba kasesi',
                            'spatula',
                            'ocak',
                            'süzgeç',
                            'çaydanlık',
                            'tepsi',
                            'wok tava',
                            'tahta kaşık',
                            'tabak',
                            'hotpot',
                            'fincan']},
 'Eğitim': {'Kırtasiye': ['abaküs',
                          'sırt çantası',
                          'tükenmez kalem',
                          'deney kabı',
                          'klasör',
                          'zarf',
                          'dolma kalem',
                          'posta çantası',
                          'kep',
                          'kalem kutusu',
                          'kalemtıraş',
                          'tüylü kalem',
                          'silgi',
                          'cetvel',
                          'hesap cetveli',
                          'stetoskop']},
'Giyim ve Aksesuar': {'Aksesuar': ['tokalı kemer',
                                    'zincir',
                                    'yüz pudrası',
                                    'saç tokası',
                                    'saç spreyi',
                                    'mendil',
                                    'ruj',
                                    'losyon',
                                    'maske',
                                    'kolye',
                                    'parfüm',
                                    'şapka',
                                    'güneş kremi',
                                    'peruk'],
                       'Kışlık': ['hırka',
                                  'Noel çorabı',
                                  'pelerin',
                                  'tüy boa',
                                  'kürk ceket',
                                  'makosen',
                                  'eldiven',
                                  'üst etek',
                                  'çorap',
                                  'sweatshirt',
                                  'trençkot'],
                       'Resmi': ["mezuniyet cübbesi",
                                 'papyon',
                                 'gecelik',
                                 'kimono',
                                 'laboratuvar önlüğü',
                                 'çanta',
                                 'takım elbise',
                                 'Windsor kravat'],
                       'Yazlık': ['abaya',
                                  'sütyen',
                                  'takunya',
                                  'kovboy şapkası',
                                  'kot pantolon',
                                  'tişört',
                                  'mayolar',
                                  'tek parça mayo',
                                  'mini etek',
                                  "pijama",
                                  'koşu ayakkabısı',
                                  'sandalet',
                                  'pareo',
                                  'banyo bonesi',
                                  'güneş gözlüğü',
                                  'güneş gözlükleri',
                                  'yüzme şortu']},
 'Hobi ve Eğlence': {'Müzik': ['akordeon',
                               'akustik gitar',
                               'banjo',
                               'fagot',
                               'kaset',
                               'kaset çalar',
                               'CD çalar',
                               'çello',
                               'kornet',
                               'davul',
                               'davul çubuğu',
                               'elektrikli gitar',
                               'flüt',
                               'fransız kornosu',
                               'büyük piyano',
                               'marimba',
                               'pan flüt',
                               'saksafon',
                               'çelik davul',
                               'trombon',
                               'dikey piyano',
                               'keman'],
                     'Oyun': ['balon',
                              'dürbün',
                              'yapboz',
                              'joystick',
                              'dağ çadırı',
                              'boya fırçası',
                              'rüzgar gülü',
                              'uyku tulumu',
                              'oyuncak ayı',
                              'daktilo klavyesi',
                              'çizgi roman',
                              'bulmaca']},
 'Spor ve Outdoor': {'Gym': ['halter',
                             'tandem bisiklet',
                             'yay',
                             'dambıl',
                             'dağ bisikleti',
                             'direk',
                             'kum torbası'],
                     'Koruma': ['yüzme başlığı',
                                'kurşun geçirmez yelek',
                                'kask',
                                'disk freni',
                                'futbol kaskı',
                                'diz koruyucu',
                                'şnorkel'],
                     'Top': ['beyzbol',
                             'basketbol',
                             'kroket topu',
                             'golf topu',
                             'pinpon topu',
                             'hokey puku',
                             'raket',
                             'ragbi topu',
                             'futbol topu',
                             'tenis topu',
                             'voleybol',
                             'düdük']}}

target_img = os.path.join(os.getcwd() , 'static/images')

@app.route('/')
def index_view():
    return render_template('index.html')

#Allow files with extension png, jpg and jpeg
ALLOWED_EXT = set(['jpg' , 'jpeg' , 'png', 'JPEG'])
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXT
           
# Function to load and prepare the image in right shape
def read_image(filename):

    img = Image.open(filename)
    img = img.resize((224, 224))  # Resize to match the input shape of your model
    img_array = image_utils.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    img_array = preprocess_input(img_array)  # Apply necessary preprocessing (e.g., mean subtraction)

    return img_array


#index is the main index, main is just the name of main, sub is the value of main
#index2 is the sub index, main2 is the sub name, sub2 is the value of sub

def engToTur (eng, category):
    category = category.replace('_', ' ')
    for index, (main, sub) in enumerate(eng.items()):
        for index2, (main2, sub2) in enumerate(sub.items()):
            for i in sub2:
                if category in i:
                    y= sub2.index(category)
                    print(index, index2, sub2.index(category))
                    print(subsubTur[main][main2][y])
                    return main + '--'+ main2 + '--'+ subsubTur[main][main2][y]
    return 'Not to use'
#if not to use

def find_category(classs):
    for item in newItems:
        parts = item.split(' -- ')
        if len(parts) >= 2:
            # print(parts)
            first_part = parts[0].replace(' ', '_')
            print(first_part)
            if first_part == classs:
                categoryTree = parts[1] +' -- '+ parts[2]
                return categoryTree
    return 'Not to use -- Not to use'

def base64_to_image(base64_string):
    image_data = base64.b64decode(base64_string)
    image = Image.open(BytesIO(image_data))
    
    return image

#add class names here to return the class name after argmax
@app.route('/test', methods=['POST'])
def testt():
    print(request)
    file = request.get_json()
    img = base64_to_image(file['image'])
    img.save('C:\\Users\\abobr\\Desktop\\etws.png')

    img = read_image('C:\\Users\\abobr\\Desktop\\etws.png')
    class_prediction=model.predict(img) 

    imageClass =class_names[int(np.argmax(class_prediction,axis=1))]
    if imageClass == 'not_to_use':
        top_5_indices = np.argsort(class_prediction[0])[-5:][::-1]

        # Get the class names and their probabilities for the top 5 predictions
        top_5_predictions = [(class_names[i], class_prediction[0][i]) for i in top_5_indices]


        # Print the top 5 predictions
        for i, (class_name, probability) in enumerate(top_5_predictions):
            print(f"Rank {i+1}: {class_name} with probability {probability}")
            if i == 1 :
                imageClass = class_name
    print(imageClass)

    with open('static/emojiCut/' + imageClass + '.png', "rb") as f:
        encoded_image = base64.b64encode(f.read())
        encoded_image = encoded_image.decode()
    imageClass = engToTur(subsubEng, imageClass)
    res = {'emojiClass' : imageClass, 'emoji' : encoded_image }
    return jsonify(res)


@app.route('/predict',methods=['GET','POST'])
def predict():
    if request.method == 'POST':
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = file.filename
            file_path = os.path.join('static/images', filename)
            file.save(file_path)

            img = read_image(file_path)
            class_prediction=model.predict(img) 

            imageClass =class_names[int(np.argmax(class_prediction,axis=1))]
            predicted_emoji = os.path.join('static/emojiCut',imageClass + '.png')
            #class_category = find_category(imageClass)
            class_categoryy = engToTur(subsubEng, imageClass)

            return render_template('predict.html', fruit = imageClass, emoji = predicted_emoji, 
                                   user_image = file_path, class_category=class_categoryy)
        else:
            return "Unable to read the file. Please check file extension"

if __name__ == '__main__':
    app.run(debug=False,host='10.242.43.18',port=5000)